# Generated by Django 4.1.7 on 2023-10-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='image not available', upload_to='images')),
                ('created', models.DateTimeField(auto_now=True)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_body', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
