# Generated by Django 4.2.6 on 2023-12-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
