# Generated by Django 4.2.6 on 2024-01-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='image not available', null=True, upload_to='thumbnail'),
        ),
    ]
