# Generated by Django 4.2.6 on 2024-01-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumnails',
            field=models.ImageField(blank=True, default='thumbnails/.jpg', null=True, upload_to='thumbnails'),
        ),
    ]
