# Generated by Django 4.2.6 on 2024-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_thumbnail_thumnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumnails',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='thumbnails'),
        ),
    ]
