# Generated by Django 4.2.5 on 2023-09-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image not available', upload_to='images'),
        ),
    ]
