# Generated by Django 4.2.6 on 2024-01-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_buyproduct_invoice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.savepdf'),
        ),
    ]
