# Generated by Django 4.1.7 on 2023-10-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='product',
        ),
    ]
