# Generated by Django 4.2.6 on 2024-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_thumbnail_thumnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
