# Generated by Django 4.2.6 on 2023-12-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_orderstatus_buyproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='month',
            field=models.CharField(choices=[('WAITING FOR SHIPPING', 'waiting for shipping'), ('PRODUCT ON THE WAY', 'product on the way'), ('OUT OF DELIVERY', 'out of delivery'), ('DELIVERED', 'delivered')], default='WAITING FOR SHIPPING', max_length=50),
        ),
        migrations.DeleteModel(
            name='Orderstatus',
        ),
    ]
