# Generated by Django 4.2.6 on 2024-01-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_buyproduct_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='invoice',
        ),
        migrations.AddField(
            model_name='savepdf',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.buyproduct'),
        ),
    ]
