# Generated by Django 4.2.6 on 2023-12-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_buyproduct_status_buyproduct_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproduct',
            old_name='month',
            new_name='orderstatus',
        ),
    ]
