# Generated by Django 4.2.6 on 2024-01-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_buyproduct_invoice_savepdf_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepdf',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
    ]
