# Generated by Django 4.2.6 on 2024-01-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_savepdf_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdffile'),
        ),
        migrations.DeleteModel(
            name='Savepdf',
        ),
    ]
