# Generated by Django 4.2.6 on 2024-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_product_categ_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images1')),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
    ]
