# Generated by Django 4.1.7 on 2023-10-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart_quanty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quanty',
            new_name='qty',
        ),
    ]
