# Generated by Django 4.2.6 on 2024-01-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_thumbnail_image_alter_thumbnail_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='thumbnail',
            new_name='thumbnail_img',
        ),
    ]
