# Generated by Django 4.2.6 on 2024-01-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_thumbnail_thumbnail_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail_img',
            field=models.ImageField(blank=True, default='error', null=True, upload_to='thumbnails'),
        ),
    ]
