# Generated by Django 4.1.7 on 2023-10-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_cart_qty_buyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buyproduct',
            name='qty',
        ),
    ]
