# Generated by Django 4.1.7 on 2023-10-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_buyproduct_address_remove_buyproduct_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
