# Generated by Django 4.2.6 on 2024-01-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_thumbnail_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
