# Generated by Django 4.1.7 on 2023-10-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_product_buyproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
