# Generated by Django 4.1.7 on 2023-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_buyproduct_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='purchased_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
